import { defineStore } from 'pinia'
import { ref } from 'vue'

export const popularQuests = defineStore({
  id:'popQuests',
  state:()=>({
    popularQuests:[
      {
        id:1,
        title:"Дневник смерти",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:ref(["orange","orange","orange","orange",false]),
        agerestrict:'16',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']
      },
      {
        id:2,
        title:"Insane Paranoid",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange","orange"],
        agerestrict:'16',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 18 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 19 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 19 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']


      },
      {
        id:3,
        title:"Last Way",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'6',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']
        
      },
      {
        id:4,
        title:"Карибский гамбит",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange","orange"],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']


      },
      {
        id:5,
        title:"Меч короля Артура",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange",false,false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']


      },
      {
        id:6,
        title:"Прятки в Алькатрасе",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']


      },
      {
        id:7,
        title:"Ограбление подпольного казино",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'16',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']
      },
      {
        id:8,
        title:"Тайна четырех жрецов",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика']
      },
      {
        id:9,
        title:"Сокровища бога Ра",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Семейные','Тайны прошлого']

      },
      {
        id:10,
        title:"Шепот",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'16',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']
      },
      {
        id:11,
        title:"Бессонница",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        // rates:["orange","orange","orange","orange",false],
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Нестрашные','Семейные','Тайны прошлого']

      },
      {
        id:12,
        title:"Прятки в лабиринте",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:true,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Семейные','Тайны прошлого']
      },
      {
        id:13,
        title:"Прятки в лабиринте",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:false,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные']

      },
      {
        id:14,
        title:"Прятки в лабиринте",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:false,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика']

      },
      {
        id:15,
        title:"Прятки в лабиринте",
        hover:`
        В семье не без урода. В один пасмурный день вы, как обычно, проверяете свою почту, 
        но, к вашему удивлению, вместо долгожданной посылки получаете приглашение от незнакомца, который утверждает, что является вашим дальним родственником.`,
        description:"м. Бауманская, ул. Фридриха Энгельса, д. 20, стр. 2",
        rates:["orange","orange","orange","orange",false],
        agerestrict:'12',
        reserve:false,
        showAll:false,
        quests: [
          {
            date: 'March 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'selected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'disabled'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'March 13 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'disabled'
              },
            ]
          },
          {
            date: 'March 14 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'disabled'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'unselected'
              },
              {
                value:'18:00',
                type:'disabled'
              },
              {
                value:'21:00',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 12 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'unselected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
              {
                value:'18:00',
                type:'unselected'
              },
              {
                value:'21:00',
                type:'unselected'
              },
              {
                value:'22:00',
                type:'selected'
              },
              {
                value:'23:30',
                type:'unselected'
              },
            ]
          },
          {
            date: 'April 15 2024',
            times:[
              {
                value:'10:00',
                type:'unselected'
              },
              {
                value:'12:00',
                type:'selected'
              },
              {
                value:'13:30',
                type:'unselected'
              },
              {
                value:'15:00',
                type:'unselected'
              },
              {
                value:'16:00',
                type:'disabled'
              },
            ]
          },
        ],
        categorie:['Научные','Космос и фантастика','Нестрашные','Семейные','Тайны прошлого']
      },
    ],
    searchText:'',
    countOfFinalPeople: 1
  }),
  actions:{
      changeResDate(type,value,date,idprop){
        const findedId = this.popularQuests.find((movie)=>movie.id == idprop)
        // console.log('date',findedId.quests.find(q=> q.date == date))
        const filteredTIme = findedId.quests.find(q=> q.date == date).times.find(t=>t.value == value)
        if(filteredTIme.type == 'unselected'){
          filteredTIme.type = 'selected'
          // console.log(filteredTIme)
          // console.log('allQuests',this.popularQuests)
        }else{
          filteredTIme.type = 'unselected'
        }
        // console.log(filteredTIme)
      },
      finalReserveDate(){
        localStorage.setItem('card',JSON.stringify(this.popularQuests)) 
        alert('Changes Saved')
        // console.log(this.popularQuests)
      },

      setReserveQuest(popcard){
        this.popularQuests = this.popularQuests.map(quest=>{
          if(quest.id === popcard.id) {
            quest.reserve =! quest.reserve
          }
          return quest
        })
        localStorage.setItem('card',JSON.stringify(this.popularQuests))  
    },

    showAll(){
      this.popularQuests = this.popularQuests.map((quest)=>{  
      if(quest.id === 13 || quest.id === 14 || quest.id === 15){
        quest.showAll = !quest.showAll
      }
        return quest
      })
      localStorage.setItem('card',JSON.stringify(this.popularQuests))  
    },

    setAllCards(cards){
      this.popularQuests = cards
    },
    calculateTotalPayment(id)  {
      let totalSelectedTimes = 0;
      const movie = this.popularQuests.find(movie => movie.id == id)
      // console.log('movie',movie)  
      movie.quests.forEach(quest => {
        const selected = quest.times.filter(time => time.type === 'selected');
        // console.log(selected)
        totalSelectedTimes += selected.length;
      });
      // console.log(totalSelectedTimes)
      return totalSelectedTimes;
    }
  },
  getters:{
    getAllQuests: (state)=>state.popularQuests,
    ShowOrLess:(state)=>{
      let findOut
      state.popularQuests.find((movie)=>{
        if(movie.id === 13){
          if(movie.showAll === true){
            findOut =  true
          }else{
            findOut = false
          }
        }
      })
      return findOut
    }
  },
})


